unit_species = {
    "marauder": "Terran",
    "reaper": "Terran",
    "ghost": "Terran",
    "viking": "Terran",
    "medivac": "Terran",
    "banshee": "Terran",
    "marine": "Terran",
    "stalker": "Protoss",
    "adept": "Protoss",
    "high_templar": "Protoss",
    "disruptor": "Protoss",
    "zealot": "Protoss",
    "phoenix": "Protoss",
    "immortal": "Protoss",
    "archon": "Protoss",
    "colossus": "Protoss",
    "observer": "Protoss",
    "oracle": "Protoss",
    "zergling": "Zerg",
    "baneling": "Zerg",
    "roach": "Zerg",
    "spine_crawler": "Zerg",
    "hydralisk": "Zerg",
}
